# Generated by Django 3.0.5 on 2020-05-07 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=6)),
                ('last_login', models.DateField()),
                ('email', models.CharField(max_length=255)),
                ('is_active', models.DateField()),
                ('date_joined', models.DateField()),
            ],
        ),
    ]
