# Generated by Django 3.0.5 on 2020-05-09 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('completed', models.BooleanField()),
                ('created_on', models.DateField(auto_now=True)),
                ('task_date', models.DateField()),
                ('completed_date', models.DateField()),
            ],
        ),
    ]
